ShopApp.UI/Models/Category.cs
namespace ShopApp.UI.Models
{
    public class Category
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

ShopApp.UI/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace ShopApp.UI.Models
{
    public class Product
    {
      
    }
}

ShopApp.UI/ViewModels/ProductViewModel.cs
using System.Collections.Generic;
using ShopApp.UI.Models;

namespace ShopApp.UI.ViewModels
{
    public class ProductViewModel
    {
        
        public List<Product> Products { get; set; } 
    }
}

ShopApp.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ShopApp.UI.Data;
using ShopApp.UI.Models;
using ShopApp.UI.ViewModels;

namespace ShopApp.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(int id)
        {
            var productViewModel = new ProductViewModel()
            {
                Products = ProductRepository.Products
            };

            return View(productViewModel);
        }
    }
}

ShopApp.UI/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopApp.UI.Data;
using ShopApp.UI.Models;
using ShopApp.UI.ViewModels;

namespace ShopApp.UI.Controllers
{


    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            var product = new Product {Name = "Iphone X", Price = 6000, Description = "güzel telefon"};

            // ViewData["Category"] = "Telefonlar";
            // ViewData["Product"] = product;

            ViewBag.Category = "Telefonlar";
            // ViewBag.Product = product;

            // ViewBag.Product
            return View(product);
        }


        // product/list => tüm ürünleri (sayfalama)
        // product/list/2 => 2 numaralı kategoriye ait ürünler
        public IActionResult list(int? id, string q, double? min_price, double? max_price)
        {
            // {controller}/{action}/{id?}
            // product/list/3
            // RouteData.Values["controller"] => product
            // RouteData.Values["action"] => list
            // RouteData.Values["id"] => 3

            // Console.WriteLine(RouteData.Values["controller"]);
            // Console.WriteLine(RouteData.Values["action"]);
            // Console.WriteLine(RouteData.Values["id"]);

            // QueryString
            // Console.WriteLine(q);
            // Console.WriteLine(HttpContext.Request.Query["q"].ToString());
            // Console.WriteLine(HttpContext.Request.Query["min_price"].ToString());

            var products = ProductRepository.Products;

            if (id != null)
            {
                products = products.Where(p => p.CategoryId == id).ToList();
            }

            if (!string.IsNullOrEmpty(q))
            {
                products = products.Where(i => i.Name.Contains(q) || i.Description.Contains(q)).ToList();
            }

            var productViewModel = new ProductViewModel()
            {
                Products = products
            };

            return View(productViewModel);
        }

        public IActionResult Details(int id)
        {
            return View(ProductRepository.GetProductById(id));
        }

        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "CategoryId", "Name");
            return View(new Product());
        }

        [HttpPost]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                ProductRepository.AddProduct(product);
                return RedirectToAction("list");

            }

            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "CategoryId", "Name");

            return View(product);

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(CategoryRepository.Categories, "CategoryId", "Name");
            return View(ProductRepository.GetProductById(id));
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            ProductRepository.EditProduct(product);
            return RedirectToAction("list");
        }

        [HttpPost]
        public IActionResult Delete(int ProductId)
        {
            ProductRepository.DeleteProduct(ProductId);
            return RedirectToAction("list");
        }
    }
}

ShopApp.UI/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ShopApp.UI.Data;
using ShopApp.UI.Models;

namespace ShopApp.UI.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString() == "list")
            {
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            }


            return View(CategoryRepository.Categories);
        }
    }
}

ShopApp.UI/Views/Home/Index.cshtml
@model ShopApp.UI.ViewModels.ProductViewModel



@{
    var popularClass = Model.Products.Count>2? "popular":"";
    var products = Model.Products;
}

@section MessageBox
{
    <div class="alert alert-warning text-center m-0">
        You have a message!
    </div>
}
@section Header
{
    <partial name ="_header"></partial>
}

@if(products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">                  
        @foreach (var product in products)
        {    
            <div class="col-md-3">
                @await Html.PartialAsync("_product", product)   
            </div>       
        }   
    </div>
}

ShopApp.UI/Views/Home/MyView.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>

home/index
</body>
</html>

ShopApp.UI/Views/Product/Create.cshtml
@model Product
<form method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input type="text" name="ImageUrl" value="@Model.Name" class="form-control">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seciniz</option>
        </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ShopApp.UI/Views/Product/Details.cshtml
@model Product

@section Categories{
    @await Component.InvokeAsync("Categories")

}

<div class="card mb-3">
    <div class="card-body">

        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="~/img/@Model.ImageUrl" class="card-img">
            </div>
            <div class="col-md-9">
                <h5 class="card-title">@Model.Name</h5>
                <p class="card-text">@Model.Description</p>
                <p class="card-text">
                    <smal class="text-muted">3 days ago</smal>
                </p>
            </div>
        </div>
    </div>
</div>

ShopApp.UI/Views/Product/Edit.cshtml
@model Product
<form method="POST">
    <input type="hidden" name="ProductId" value="@Model.ProductId">
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description"value="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input type="text" name="ImageUrl" value="@Model.ImageUrl" class="form-control">
    </div>
    <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seciniz</option>


        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ShopApp.UI/Views/Product/Index.cshtml
@section Categories
{
    @await Component.InvokeAsync("Categories")
}


product index

ShopApp.UI/Views/Product/List.cshtml
@model ShopApp.UI.ViewModels.ProductViewModel


@{
    var popularClass = Model.Products.Count>2? "popular":"";
    var products = Model.Products;
}

@section Categories
{
    @await Component.InvokeAsync("Categories")
}

@if(products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">                  
        @foreach (var product in products)
        {    
            <div class="col-md-4">
                @await Html.PartialAsync("_product", product)   
            </div>       
        }   
    </div>
}

ShopApp.UI/Views/Shared/Components/Categories/Default.cshtml
<div class="list-group">
    <a asp-controller="Product" asp-action="List" class="list-group-item list-group-item-action">Tüm Kategoriler</a>

    @foreach (var category in Model)
    {
        <a asp-controller="Product" asp-action="List"
           asp-route-id="@category.CategoryId"
           class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == category.CategoryId.ToString()?"active": "")">@category.Name</a>
    }
</div>

ShopApp.UI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
             <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
<link rel="stylesheet" href="~/css/style.css"/>

             <title>Document</title>
</head>
<body>


@if(IsSectionDefined("MessageBox"))
{
    @RenderSection("MessageBox")
}
else
{
    <div class="alert alert-primary text-center m-0">
        Welcome!
    </div>
}

@await Html.PartialAsync("_navbar")
@RenderSection("Header",false)


<main class="my-3">
    <div class="container"> 

        @if(IsSectionDefined("Categories"))
        {
            <div class="row">
                <div class="col-md-3">
                    @RenderSection("Categories",false)
                </div>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        }   
        else
        {
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>   
        }
            
    </div>
</main>

<footer class="py-5 bg-dark text-white text-center">
    Shop App | 2020
</footer>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

@RenderSection("Scripts",false)
</body>
</html>

ShopApp.UI/Views/Shared/_Layout2.cshtml
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
             <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

             <title>Document</title>
</head>
<body style="background-color: yellow">
  @await Html.PartialAsync("_navbar")
<partial name="_header"/>
<main>
    <div class="container">
        
        @RenderBody()

    </div>
</main>

</body>
</html>

ShopApp.UI/Views/Shared/_categories.cshtml
@model List<Category>

<div class="list-group">
    @foreach (var category in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@category.Name</a>
    }
</div>

ShopApp.UI/Views/Shared/_header.cshtml
<header>
    <div class="jumbotron jumbotron-fluid">

        <div class="container">
            <h1 class="displasy-4">Shopp App</h1>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero, nisi!</p>
        </div>
    </div>


</header>

ShopApp.UI/Views/Shared/_navbar.cshtml
<div class="navbard bg-primary navbar-dark navbar-expand-sm">
    <div class="container">

        <ul class="navbar-nav">

            <li class="nav-item">
                <a href="/product/list" class="nav-link">Products 1</a>
            </li>
            <li class="nav-item">
                <a href="/product/create" class="nav-link">Add Product</a>

            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">Link 3</a>
            </li>
        </ul>
        
        <form action="/product/list" class="form-inline">
            <input name ="query" type="text" class="form-control mr-2" placeholder="Search">
            <button type="submit" class="btn btn-outline-light mr-0">Search</button>
        </form>
    </div>

</div>

ShopApp.UI/Views/Shared/_noproduct.cshtml
  <div class="row">
                <div class="col-md 12">
                    <div class="alert alert-danger">
                        Urun yok
                    </div>
                </div>

            </div>

ShopApp.UI/Views/Shared/_product.cshtml
@model Product                        
<div class="card mb-2">
    <img src="~/img/@Model.ImageUrl" alt="" class="card-img-top">

    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>


        <a asp-controller="Product" asp-action="Details" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">Incele</a>
        <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">Edit</a>

        <form method="POST" action="/product/delete" style="display: inline;">
            <input type="hidden" name="ProductId" value="@Model.ProductId"/>
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
        </form>


    </div>
</div>